cache: pip

dist: xenial

language: python

python:
  - "3.6"

jobs:
  include:

    - name: Unit Tests
      env:
        CACHE_NAME: unit-tests
      addons:
        apt:
          packages:
            - postgresql-11
        postgresql: "11"
      install:
        - pip install pytest-cov python-coveralls -r requirements.txt -r test-requirements.txt
      script:
        - python setup.py test --addopts='-vv --durations=0 --cov coveralls --cov-report term-missing'
      after_success:
        - coveralls

    - name: Lint
      env:
        CACHE_NAME: lint
      install:
        - pip install flake8
      script:
        - flake8 --show-source growth
