cache: pip

dist: xenial

language: python

python:
  - "3.6"

jobs:
  include:

    - name: Unit Tests
      env:
        CACHE_NAME: unit-tests
      addons:
        apt:
          packages:
            - postgresql-11
        postgresql: "11"
      install:
        - pip install pytest-cov coveralls -r requirements.txt -r test-requirements.txt
        # FIXME: Fixes a Unicode warning that clutters up unit test logs.
        # See https://github.com/pallets/flask-sqlalchemy/issues/671
        - pip install git+https://github.com/pallets/flask-sqlalchemy@2.x
        - pip install -r requirements.txt
        - python -c 'from astropy.coordinates import EarthLocation; from astroplan import download_IERS_A; EarthLocation.get_site_names(); download_IERS_A()'
      script:
        - python setup.py test --addopts='-vv --durations=0 --cov'
      after_success:
        - coveralls

    - name: Lint
      env:
        CACHE_NAME: lint
      install:
        - pip install flake8
      script:
        - flake8 --show-source growth
