language: python
dist: xenial
python:
  - "3.6"
jobs:
  include:
    - name: Unit Tests
      addons:
        postgresql: "11"
        apt:
          packages:
            - postgresql-11
      install:
        - pip install python-coveralls -r requirements.txt
      script:
        - python setup.py test --addopts='--cov coveralls --cov-report term-missing'
      after_success:
        - coveralls
    - name: Lint
      install:
        - pip install flake8
      script:
        - flake8 --show-source growth
